import bcrypt from 'bcrypt';
import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex.raw('SET FOREIGN_KEY_CHECKS=0');
  await knex('users').truncate();
  await knex.raw('SET FOREIGN_KEY_CHECKS=1');

  // Default dev password for all seed users: Senha123
  const passwordHash = await bcrypt.hash('Senha123', 12);

  await knex('users').insert([
    {
      id: 602,
      first_name: 'Elisa',
      last_name: 'Pereira',
      user_name: 'elisa.pereira',
      password_hash: passwordHash,
      index_ref: 17,
      created_at: new Date('2017-02-15T11:29:40.799Z'),
      token: '',
    },
    {
      id: 903,
      first_name: 'Enzo',
      last_name: 'Barros',
      user_name: 'enzo_barros',
      password_hash: passwordHash,
      index_ref: 18,
      created_at: new Date('2018-03-28T00:53:08.981Z'),
      token: '',
    },
    {
      id: 470,
      first_name: 'Danilo',
      last_name: 'Carvalho',
      user_name: 'danilo95',
      password_hash: passwordHash,
      index_ref: 9,
      created_at: new Date('2020-04-23T12:32:02.614Z'),
      token: '',
    },
    {
      id: 115,
      first_name: 'Talita',
      last_name: 'Melo',
      user_name: 'talita.melo',
      password_hash: passwordHash,
      index_ref: 3,
      created_at: new Date('2017-04-23T19:24:43.992Z'),
      token: '',
    },
    {
      id: 812,
      first_name: 'Heloisa',
      last_name: 'Albuquerque',
      user_name: 'heloisa.albuquerque',
      password_hash: passwordHash,
      index_ref: 19,
      created_at: new Date('2015-04-23T05:19:20.309Z'),
      token: '',
    },
    {
      id: 111,
      first_name: 'Emanuel',
      last_name: 'Carvalho',
      user_name: 'emanuel.carvalho',
      password_hash: passwordHash,
      index_ref: 13,
      created_at: new Date('2018-01-11T19:22:49.010Z'),
      token: '',
    },
    {
      id: 453,
      first_name: 'Murilo',
      last_name: 'Nogueira',
      user_name: 'murilo_nogueira',
      password_hash: passwordHash,
      index_ref: 5,
      created_at: new Date('2020-07-29T03:50:46.143Z'),
      token: '',
    },
    {
      id: 90,
      first_name: 'Maria Eduarda',
      last_name: 'Costa',
      user_name: 'mariaeduarda_costa12',
      password_hash: passwordHash,
      index_ref: 12,
      created_at: new Date('2017-05-28T18:06:23.242Z'),
      token: '',
    },
    {
      id: 958,
      first_name: 'Marcelo',
      last_name: 'Carvalho',
      user_name: 'marcelo_carvalho',
      password_hash: passwordHash,
      index_ref: 4,
      created_at: new Date('2019-09-30T19:31:56.383Z'),
      token: '',
    },
    {
      id: 592,
      first_name: 'Salvador',
      last_name: 'Moraes',
      user_name: 'salvador.moraes',
      password_hash: passwordHash,
      index_ref: 16,
      created_at: new Date('2020-09-28T07:17:47.496Z'),
      token: '',
    },
    {
      id: 502,
      first_name: 'Morgana',
      last_name: 'Santos',
      user_name: 'morgana_santos',
      password_hash: passwordHash,
      index_ref: 15,
      created_at: new Date('2015-05-04T21:11:19.998Z'),
      token: '',
    },
    {
      id: 247,
      first_name: 'Alice',
      last_name: 'Barros',
      user_name: 'alice_barros38',
      password_hash: passwordHash,
      index_ref: 20,
      created_at: new Date('2020-06-09T15:15:18.832Z'),
      token: '',
    },
    {
      id: 935,
      first_name: 'John Peter',
      last_name: 'Santos',
      user_name: 'johnpeter_santos5',
      password_hash: passwordHash,
      index_ref: 7,
      created_at: new Date('2017-07-28T00:30:30.030Z'),
      token: '',
    },
    {
      id: 374,
      first_name: 'Feliciano',
      last_name: 'Moreira',
      user_name: 'feliciano.moreira',
      password_hash: passwordHash,
      index_ref: 11,
      created_at: new Date('2016-05-08T12:05:05.850Z'),
      token: '',
    },
    {
      id: 30,
      first_name: 'Bernardo',
      last_name: 'Carvalho',
      user_name: 'bernardo41',
      password_hash: passwordHash,
      index_ref: 10,
      created_at: new Date('2018-04-04T02:39:40.040Z'),
      token: '',
    },
    {
      id: 439,
      first_name: 'Isaac',
      last_name: 'Martins',
      user_name: 'isaac55',
      password_hash: passwordHash,
      index_ref: 6,
      created_at: new Date('2020-05-04T08:59:15.150Z'),
      token: '',
    },
    {
      id: 352,
      first_name: 'Carla',
      last_name: 'Batista',
      user_name: 'carla.batista',
      password_hash: passwordHash,
      index_ref: 14,
      created_at: new Date('2020-01-18T09:23:51.360Z'),
      token: '',
    },
    {
      id: 5,
      first_name: 'Hugo',
      last_name: 'Reis',
      user_name: 'hugo25',
      password_hash: passwordHash,
      index_ref: 2,
      created_at: new Date('2015-10-18T00:56:33.330Z'),
      token: '',
    },
    {
      id: 29,
      first_name: 'Rafaela',
      last_name: 'Saraiva',
      user_name: 'rafaela.saraiva91',
      password_hash: passwordHash,
      index_ref: 8,
      created_at: new Date('2019-10-07T20:17:43.740Z'),
      token: '',
    },
    {
      id: 771,
      first_name: 'Marcia',
      last_name: 'Carvalho',
      user_name: 'marcia_carvalho81',
      password_hash: passwordHash,
      index_ref: 1,
      created_at: new Date('2016-12-08T00:49:39.990Z'),
      token: '',
    },
  ]);
}
