import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex.raw('SET FOREIGN_KEY_CHECKS=0');
  await knex('posts').truncate();
  await knex.raw('SET FOREIGN_KEY_CHECKS=1');

  await knex('posts').insert([
    {
      id: 645,
      title: 'Nemo rerum dolorem.',
      body: 'Accusantium quis est molestiae. Aliquam voluptatem rerum eaque. Nihil error nam voluptates aut eum libero. Est quasi hic dolor itaque. Quis officia distinctio et non itaque. Voluptate odio enim.\n \rAutem ut blanditiis incidunt temporibus voluptatem consequatur vero harum itaque. Aut eveniet unde dolores consequatur et. Id sequi deleniti incidunt. Vitae et magni.\n \rConsectetur aperiam error tempora at harum maxime. Repellat et voluptas. Sint nesciunt animi aperiam sed maxime qui mollitia nihil. Aut illo labore voluptatem quia minus.',
      user_id: 115,
      index_ref: 1,
      created_at: new Date('2020-12-19T19:25:24.495Z'),
    },
    {
      id: 50,
      title: 'Enim et provident rem.',
      body: 'Explicabo placeat ut quis. Qui et accusantium repellat quaerat ut laboriosam. Sunt ea asperiores. Molestiae fugiat ut. Possimus natus cum in ut.\n \rVelit laborum enim accusamus voluptatem est quae et aut quis. Nesciunt dolores earum aliquid atque eos ipsa harum quidem est. Sint a assumenda sunt velit. Ipsa dicta nemo quia assumenda eos omnis dolorem repellat. Dicta expedita dolorem illum vel. Error facere ut explicabo minima.\n \rDicta quae illo non voluptas nesciunt cupiditate. Sequi dolorem cum. Quis et doloremque harum consequatur quibusdam est expedita. Hic occaecati esse placeat voluptas iure sed qui quidem fugit. Quis ratione dicta asperiores et.',
      user_id: 115,
      index_ref: 2,
      created_at: new Date('2019-01-11T02:47:06.328Z'),
    },
    {
      id: 361,
      title: 'Ad nihil magni atque.',
      body: 'Laudantium qui accusamus deleniti velit nulla eligendi harum maxime nobis. Vitae sint totam et. Ipsa totam est error est dolor nostrum aperiam tenetur unde. Sit labore dolores et dignissimos voluptatem veniam quae.\n \rMolestiae qui quas est ipsa sunt. Tempore cum non ipsum. Est aspernatur voluptas autem repellat consectetur rem quos soluta.\n \rVoluptas quia quia quis ipsam explicabo aliquid similique necessitatibus officia. Voluptatum dicta ut. Aliquam quia odio sunt cumque dolorem doloremque.\n \rVitae ipsum soluta ducimus et. Vitae adipisci in vel et ad ratione aut quidem laboriosam. Dolor velit fuga est consequuntur quibusdam voluptate. Autem soluta in aut earum iusto consectetur unde veniam omnis.\n \rMollitia voluptatem porro omnis. Deserunt debitis ducimus tenetur. Aut molestiae harum. A voluptas labore fugiat tempore odit incidunt.',
      user_id: 115,
      index_ref: 3,
      created_at: new Date('2016-06-07T15:31:52.589Z'),
    },
    {
      id: 342,
      title: 'Maiores ex tempore quo qui.',
      body: 'Earum natus quis possimus iusto voluptatem dicta. Facilis voluptate minima architecto similique quas. Tempora illum omnis aut et id minima nihil itaque quo. Dicta ratione ut voluptates quia harum voluptates qui.\n \rVoluptas velit qui eum sit voluptatem animi aut provident enim. Sed magnam reiciendis. Natus et fugit omnis quaerat iusto iste aliquam dignissimos magnam.',
      user_id: 115,
      index_ref: 4,
      created_at: new Date('2016-06-05T20:17:46.223Z'),
    },
    {
      id: 704,
      title: 'Itaque voluptas et tempora dolor dolor amet dolor ut.',
      body: 'Debitis praesentium facere odit similique in sed necessitatibus. Possimus quidem et. Aliquid labore placeat rerum hic nulla.\n \rNon et ducimus. Ex incidunt qui qui quibusdam laboriosam consequatur accusantium. Ut qui blanditiis est quam rerum provident. Aut et qui ut culpa voluptate. Magni quod culpa aliquam recusandae rem odit iste cupiditate blanditiis.\n \rMolestias alias vel dolores blanditiis. A eveniet eum iste sapiente. Deleniti voluptatibus magni assumenda quo aperiam non voluptatum similique.',
      user_id: 115,
      index_ref: 5,
      created_at: new Date('2017-10-21T11:29:55.549Z'),
    },
    {
      id: 861,
      title: 'Dolores consequatur eos in ipsa et quasi sequi.',
      body: 'Non est earum omnis. Optio earum ex ut. Id quae voluptatem. Deleniti maxime aut voluptatem quasi placeat aliquid sunt.\n \rMolestiae quia et veniam provident quia. Sed et asperiores sed est non dolore. Porro sed blanditiis voluptatum voluptatum aut unde odit nobis. Dicta animi sit nisi ipsam nesciunt praesentium non cumque.\n \rA culpa consequatur dolores amet temporibus dicta voluptatem ab. Odit accusantium rerum et sapiente accusamus. Sint sit asperiores qui molestiae. Sunt laudantium cumque nobis dolor.',
      user_id: 115,
      index_ref: 6,
      created_at: new Date('2018-10-31T18:06:19.757Z'),
    },
    {
      id: 481,
      title: 'Molestias nobis sunt eum totam.',
      body: 'Consequatur natus quae quisquam laudantium est. Aut omnis autem nulla et ipsum sint. Et consectetur fugiat magni et laboriosam. Dolor magni vero magnam dignissimos sed iure qui. Voluptatem maiores aut quasi voluptas. Doloribus illum alias qui dolorum est.\n \rEst nostrum sequi et velit sunt est. Ipsum est atque dolore. Dolores nihil rem. Consequatur fugiat vel non cupiditate ut. Maxime unde aliquid.\n \rImpedit fugit minima voluptatem. Error labore enim rerum aut qui aut soluta eum. Itaque reprehenderit minima veritatis distinctio voluptas dolores. Non accusantium facere non occaecati saepe necessitatibus id est.',
      user_id: 29,
      index_ref: 7,
      created_at: new Date('2015-12-11T00:40:59.233Z'),
    },
    {
      id: 140,
      title: 'Quia dignissimos veniam neque itaque.',
      body: 'Nisi doloremque esse ex. Aliquid nam optio et ut facilis qui incidunt nisi et. Magni iure labore doloremque ut.',
      user_id: 29,
      index_ref: 8,
      created_at: new Date('2015-08-30T09:35:49.728Z'),
    },
    {
      id: 455,
      title: 'Culpa consequatur dicta dignissimos.',
      body: 'Animi perspiciatis aut quia laborum repellat. Nobis ut qui odit aliquid tenetur. Dolorem porro earum quisquam deleniti debitis fuga vel officiis. Veritatis sed sint. Qui reiciendis at illo dolorem corrupti harum.\n \rNostrum repellendus sunt rerum soluta perspiciatis. Et consequatur fuga sed explicabo. In quas aut quas odio a tenetur in commodi provident. Odit qui molestias ut error placeat ipsam neque. Ea impedit voluptatem laboriosam voluptates pariatur fugiat facilis quo. Nostrum optio qui reprehenderit dolorem omnis accusantium possimus corrupti cumque.\n \rVoluptatem nesciunt dolorem libero. Similique aut et cupiditate omnis sit sint tenetur qui voluptatem. Blanditiis quo ea nihil recusandae et nobis molestiae. Nemo est et. Odio quis unde. Quae debitis qui iusto dolorem dolores nemo.',
      user_id: 29,
      index_ref: 9,
      created_at: new Date('2021-02-22T14:54:03.421Z'),
    },
    {
      id: 860,
      title: 'Et voluptatem nulla omnis et iusto ullam.',
      body: 'Ad non pariatur. Aut molestias accusamus et inventore sunt voluptates non doloremque illum. Perspiciatis et provident vel et fugiat dolores ut. Quos quibusdam impedit cupiditate quia at eaque quae.',
      user_id: 29,
      index_ref: 10,
      created_at: new Date('2018-08-10T23:41:51.714Z'),
    },
    {
      id: 49,
      title:
        'Qui facere repellat dolor sint quos quam consequatur sed asperiores.',
      body: 'Distinctio atque amet doloribus vero doloremque et est nobis. Vel molestiae quidem ut qui quasi quas officiis ut. Aut amet nihil asperiores repellendus eos. Sint amet odio itaque et. Omnis voluptatibus quia id exercitationem enim aspernatur possimus voluptatum atque. Veritatis odio dolor voluptas.\n \rRepudiandae dolor impedit. Saepe vitae non facere cumque qui sunt harum. Et cupiditate quia. Omnis labore quae quisquam alias occaecati labore dolorem laborum sit.\n \rNesciunt velit provident non similique asperiores. Repellat deserunt atque sed aut non sunt. Porro sed dolores cumque. Ipsum sapiente similique ipsam ex fugiat in. Deserunt vero molestiae commodi fugiat voluptatem pariatur.',
      user_id: 247,
      index_ref: 11,
      created_at: new Date('2019-09-07T06:51:26.519Z'),
    },
    {
      id: 940,
      title:
        'Similique impedit consequatur qui ipsam sint quam rerum dolores distinctio.',
      body: 'Quidem nisi saepe omnis quia repudiandae odio. Eius quia quis inventore. Illo nihil voluptas est. Quo atque facilis autem velit. Aspernatur quia labore eveniet dolorum.',
      user_id: 903,
      index_ref: 12,
      created_at: new Date('2015-08-28T14:07:58.674Z'),
    },
    {
      id: 971,
      title: 'Ducimus tenetur officiis in unde repudiandae porro.',
      body: 'Consequatur vero voluptatem quis vero eveniet sed magnam debitis accusamus. Natus et aut eius nisi non voluptatem et. Expedita labore sed eveniet quis veritatis veniam dolorum quo. Inventore id iste doloremque qui eum adipisci eum vel omnis.',
      user_id: 903,
      index_ref: 13,
      created_at: new Date('2019-05-30T19:48:26.635Z'),
    },
    {
      id: 513,
      title: 'Aut sequi placeat ea exercitationem perferendis.',
      body: 'Nemo optio iure sapiente excepturi. Ut nam iste dolorem aliquid. Quisquam ducimus velit voluptas laudantium eveniet aut. Ipsum qui non et omnis sed sint aut. Impedit voluptatem porro ratione iure dolorum.',
      user_id: 958,
      index_ref: 14,
      created_at: new Date('2017-12-30T06:30:06.984Z'),
    },
    {
      id: 572,
      title: 'Nulla sunt sint et et officia voluptatem itaque.',
      body: 'Quam voluptatem at reprehenderit nesciunt qui est aperiam aut voluptas. Deserunt maiores non rerum numquam impedit quibusdam maxime consequatur. Perspiciatis sit cumque tenetur accusantium rem qui.',
      user_id: 958,
      index_ref: 15,
      created_at: new Date('2016-11-19T22:23:52.689Z'),
    },
    {
      id: 833,
      title:
        'Aliquam sit doloremque eos debitis rerum eum odit quaerat incidunt.',
      body: 'Velit qui expedita aliquam voluptatem recusandae sed adipisci qui maiores. Blanditiis perspiciatis eius. Quia illo quos quaerat suscipit. Nulla dolor accusamus. Cumque nobis totam. Tempore ut placeat repellat sed quo sed.',
      user_id: 958,
      index_ref: 16,
      created_at: new Date('2021-01-20T23:50:26.272Z'),
    },
    {
      id: 277,
      title: 'Aut modi non ab animi velit rerum.',
      body: 'Sequi dignissimos nihil perferendis vel amet officiis in. Consequatur rem facilis id nobis ea nihil. At dolor et eos reprehenderit deleniti occaecati dolore est doloremque.',
      user_id: 502,
      index_ref: 17,
      created_at: new Date('2015-11-30T05:04:23.271Z'),
    },
    {
      id: 856,
      title:
        'Repellendus fugiat officiis quisquam asperiores aliquid dignissimos.',
      body: 'Quisquam quas quia rerum blanditiis autem. Odit harum possimus sit dolor voluptatem aliquid facilis corporis. Rerum magnam qui optio voluptates tenetur et totam qui occaecati. Libero et ut. Laborum placeat veritatis sit quod corporis quia ipsam qui. Dolores ut quia tempore rerum beatae.',
      user_id: 502,
      index_ref: 18,
      created_at: new Date('2021-04-23T08:30:50.947Z'),
    },
    {
      id: 601,
      title: 'Nihil numquam eum iure consequatur.',
      body: 'Repellendus nam voluptates quis accusantium non similique. Adipisci et praesentium maxime ab. Sunt voluptatibus iusto iste commodi alias ut saepe et.',
      user_id: 502,
      index_ref: 19,
      created_at: new Date('2017-04-26T19:39:05.420Z'),
    },
    {
      id: 638,
      title: 'Maxime qui magnam saepe ullam.',
      body: 'Illo quod reprehenderit. Consequatur quasi eius et a velit. Quia hic voluptates dolores ratione. Aut quo non quia et iure porro nesciunt voluptas ratione. Aperiam dolor deleniti dolores qui vitae et ipsum. Repellat ex dolor rerum sit quos.',
      user_id: 502,
      index_ref: 20,
      created_at: new Date('2016-12-28T22:35:28.886Z'),
    },
    {
      id: 666,
      title: 'Doloremque sit atque dolor rem non ut voluptates quod maiores.',
      body: 'Facere fugit voluptates dolor enim illo consequatur ipsa cupiditate. Assumenda minima facere ratione. Voluptas laborum ipsa eveniet impedit magnam in. Molestiae consectetur enim. Ullam eius delectus beatae aut. Qui aut et magni nihil et et illo.',
      user_id: 502,
      index_ref: 21,
      created_at: new Date('2020-03-27T17:21:33.103Z'),
    },
    {
      id: 783,
      title: 'Autem non temporibus sequi.',
      body: 'Ipsam blanditiis amet. Sapiente sed eos earum qui consequatur natus quia voluptatem nihil. Non eum omnis aut sed autem et recusandae vel. Explicabo et temporibus quod voluptatem. Dolores debitis accusamus dolore aut fuga sunt. Et explicabo voluptates tenetur sed voluptatem repellendus est officia.',
      user_id: 502,
      index_ref: 22,
      created_at: new Date('2021-04-01T01:06:47.589Z'),
    },
    {
      id: 15,
      title: 'Velit culpa dolorem libero velit sed temporibus omnis.',
      body: 'Laudantium accusamus sit excepturi aut voluptatem. Sed aliquam accusamus et dicta debitis. Quam nihil iusto ullam repudiandae.\n \rAutem aperiam officiis quia eius quis esse. Quos eos at facilis non ut. Molestiae ea dolor. Pariatur totam aliquam totam aut necessitatibus quis dolor.',
      user_id: 439,
      index_ref: 23,
      created_at: new Date('2020-04-22T04:29:45.812Z'),
    },
    {
      id: 607,
      title: 'Laborum optio sunt aut ut ut ut.',
      body: 'Sit sed deserunt libero nulla in culpa. Culpa quasi ullam quaerat dolorem assumenda molestiae. Doloribus autem possimus beatae esse optio consectetur. Ut veritatis sint voluptatem minima occaecati ab id sed optio. Qui laudantium hic iusto voluptatibus quis sed exercitationem ut mollitia.',
      user_id: 439,
      index_ref: 24,
      created_at: new Date('2019-02-12T01:13:25.622Z'),
    },
  ]);
}
