mutation CREATE_POST {
  createPost(data: { title: "The title", body: "The content", userId: "592" }) {
    id
    title
    body
    user {
      firstName
    }
    indexRef
    createdAt
  }
}

mutation UPDATE_POST {
  updatePost(postId: "3vgV_ff", data: { title: "UPDATED - The title" }) {
    id
    title
    body
    user {
      firstName
    }
    indexRef
    createdAt
  }
}

mutation DELETE_POST {
  deletePost(postId: "3vgV_ff")
}

mutation CREATE_USER {
  createUser(
    data: { firstName: "John", lastName: "Miranda", userName: "john-miranda1" }
  ) {
    id
    firstName
    lastName
    userName
    indexRef
    createdAt
    posts {
      id
    }
  }
}

mutation UPDATE_USER {
  updateUser(
    userId: "VhsZF-7"
    data: {
      firstName: "NEWFIRST"
      lastName: "New last"
      userName: "new.user-name"
    }
  ) {
    id
    firstName
    lastName
    userName
    indexRef
    createdAt
    posts {
      id
    }
  }
}

mutation DELETE_USER {
  deleteUser(userId: "VhsZF-7")
}
